Issue 11
cancervariants/therapy-normalization pull request #23
Opened 2020-10-09 14:01 UTC by jsstevenson

Close #11 

Adds optional parameters to search endpoint allowing for inclusion or exclusion of normalizers, and for returning key-value-formatted response (for dgidb compatibility)

2020-10-09 14:57 UTC, korikuzma requested changes

2020-10-09 14:57 UTC, korikuzma commented on therapy/normalizers/chembl.py
> +                    'https://creativecommons.org/licenses/by-sa/3.0/')
Remove this

2020-10-12 16:53 UTC, jsstevenson commented on therapy/normalizers/chembl.py
> +                    'https://creativecommons.org/licenses/by-sa/3.0/')
Removed!

2020-10-12 16:56 UTC, korikuzma approved these changes

2020-10-12 16:59 UTC, merged