fix: handle label and order by biologic suffix in merge groups
cancervariants/therapy-normalization pull request #418
Opened 2024-04-12 14:17 UTC by jsstevenson

close #299 

Two related issues 
1) If a normalized drug already has a label, other labels in the group should be added as aliases
2) RxNorm provides records for biosimilars that have a [four character suffix](https://www.faegredrinker.com/en/insights/publications/2017/1/whats-in-a-name-a-fourletter-suffix-to-be-fda-compliant#:~:text=The%20FDA%20explained%20that%20it,have%20not%20been%20deemed%20interchangeable) but are otherwise the same as the base drug in their name. That base name should be the label of the normalized group, and the drug labeled with that name should be the primary concept ID for the group.

2024-04-12 18:29 UTC, korikuzma requested changes

2024-04-12 18:29 UTC, korikuzma commented on src/therapy/etl/merge.py
> +            """Provide priority values of concepts for sort function."""
add param, return, raises in docstrings

2024-04-12 20:18 UTC, jsstevenson commented on src/therapy/etl/merge.py
> +            """Provide priority values of concepts for sort function."""
oh wow this is old

2024-04-13 18:18 UTC, korikuzma approved these changes

2024-04-15 20:25 UTC, merged