Dynamodb refactor
cancervariants/therapy-normalization pull request #54
Opened 2020-12-02 18:25 UTC by jsstevenson

Various production-oriented additions:
 * Show docs at root endpoint
 * Break up production and dev dependencies
 * Refactor normalizer/database as classes
 * etc

2020-12-02 18:53 UTC, korikuzma requested changes
Need to add dev db_url

2020-12-02 18:53 UTC, korikuzma commented on tests/unit/test_chembl_source.py
> +    """Build Wikidata normalizer test fixture."""
```suggestion
    """Build ChEMBL normalizer test fixture."""
```

2020-12-02 18:53 UTC, korikuzma commented on tests/unit/test_drugbank_source.py
> +    """Build Wikidata normalizer test fixture."""
```suggestion
    """Build DrugBank normalizer test fixture."""
```

2020-12-02 18:53 UTC, korikuzma commented on tests/unit/test_ncit_source.py
> +    """Build Wikidata normalizer test fixture."""
```suggestion
    """Build NCIt normalizer test fixture."""
```

2020-12-02 18:53 UTC, korikuzma commented on tests/unit/test_therapy_query.py
> +    """Build Wikidata normalizer test fixture."""
```suggestion
    """Build normalizer test fixture."""
```

2020-12-02 18:53 UTC, korikuzma commented on therapy/database.py
> +                                             endpoint_url=db_url)
This never gets called. We should add a flag in cli.py to determine if we are in dev/prod

2020-12-02 18:53 UTC, korikuzma commented on therapy/query.py
> +# from therapy.database import THERAPIES_TABLE, METADATA_TABLE, cached_sources
```suggestion
```

2020-12-02 18:59 UTC, korikuzma commented on cli.py
>      def update_normalizer_db(normalizer, all):
```suggestion
    @click.option(
        '--env',
        help="dev or prod"
    )
    def update_normalizer_db(normalizer, all):
```

2020-12-02 18:59 UTC, korikuzma commented on cli.py
> +        normalizers = normalizer.lower().split(',')
```suggestion
        if env == "prod":
            db: Database = Database()
        elif env == "dev":
            db: Database = Database(db_url='http://localhost:8000')
        else:
            raise Exception('Must enter dev or prod.')
            
        normalizers = normalizer.lower().split(',')
```

2020-12-02 19:12 UTC, korikuzma commented on therapy/query.py
> +        #            "drugbank": "DrugBank"}
```suggestion
```

2020-12-03 13:10 UTC, korikuzma commented on cli.py
> -    )
Why are we removing this flag? We should keep it so that users don't have to type in each normalizer.

2020-12-03 13:24 UTC, korikuzma requested changes
We need to implement the update_all flag in cli.py. 
Should we be setting the db_url in cli.py or just stick with an env variable?

2020-12-03 13:24 UTC, korikuzma commented on cli.py
> -    )
Why are we removing this flag? We should keep it so users don't have to write out each normalizer.

2020-12-03 13:24 UTC, korikuzma commented on therapy/database.py
> +                                             region_name=region_name)
```suggestion
        if 'THERAPY_NORM_DB_URL' in environ.keys():
            db_url = environ['THERAPY_NORM_DB_URL']
            self.ddb = boto3.resource('dynamodb', region_name=region_name,
                                      endpoint_url=db_url)
            self.ddb_client = boto3.resource('dynamodb',
                                             region_name=region_name,
                                             endpoint_url=db_url)
        else:
            self.ddb = boto3.resource('dynamodb', region_name=region_name)
            self.ddb_client = boto3.resource('dynamodb',
                                             region_name=region_name)
```
The first if statement never gets called.

2020-12-03 14:35 UTC, jsstevenson reviewed
👍

2020-12-03 14:41 UTC, korikuzma approved these changes
👍

2020-12-03 14:48 UTC, merged