Swagger docs
cancervariants/therapy-normalization pull request #56
Opened 2020-12-03 16:07 UTC by jsstevenson

Add/change description text as it appears on the root docs page

2020-12-03 16:20 UTC, korikuzma requested changes
Comment out adding info for now.

2020-12-03 16:20 UTC, korikuzma commented on main.py
> +    }
```suggestion
# TODO: Figure out how to add these back
    # openapi_schema['info']['license'] = {  # TODO
    #     "name": "name of our license",
    #     "url": "link to it"
    # }
    # openapi_schema['info']['contact'] = {  # TODO
    #     "name": "alex wagner",
    #     "email": "his email"
    # }
```

2020-12-03 16:20 UTC, korikuzma commented on main.py
> +                     "aggregated sources."
```suggestion
read_query_summary = "Given query, provide highest matches from "\
                     "aggregated sources."
```

2020-12-03 16:20 UTC, korikuzma commented on main.py
> +q_descr = "String to normalize."
```suggestion
q_descr = "Therapy to normalize."
```

2020-12-03 18:16 UTC, korikuzma approved these changes

2020-12-04 19:30 UTC, ahwagner requested changes
Minor edits. Looks great.

2020-12-04 19:30 UTC, ahwagner commented on main.py
> +        description="Normalize therapy terms.",
```suggestion
        description="Normalize drugs and other therapy terms.",
```

2020-12-04 19:30 UTC, ahwagner commented on main.py
>          title="Therapy Normalizer",
```suggestion
        title="The VICC Therapy Normalizer",
```

2020-12-04 19:30 UTC, ahwagner commented on main.py
> +    }
```suggestion
#    openapi_schema['info']['license'] = {  # TODO
#        "name": "Name-of-license",
#        "url": "http://www.to-be-determined.com"
#    }
```

Let's not attach a license for now.

2020-12-04 19:30 UTC, ahwagner commented on main.py
> +    }
```suggestion
    openapi_schema['info']['contact'] = {  # TODO
        "name": "Alex H. Wagner",
        "email": "Alex.Wagner@nationwidechildrens.org"
    }
```

2020-12-04 19:30 UTC, ahwagner commented on main.py
> +    """Normalize query string given by user.
```suggestion
    """Return strongest match concepts to query string provided by user.
```

2020-12-07 19:33 UTC, merged